### ISSUE TITLE
unify the format of variables documentation

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#257]
this is related mainly to `examples`, but module might require review as well
proposed format - VMSS documentation in autoscaling example

**Comment by michalbil** [comment]
First proposal from my side - use hyphen instead of colons to separate property name and description (such an approach is a standard for example in TF resources docs) and remove extra spaces from (type|required) - pipe alone is a good enough separator imo.

```hcl
description = <<-EOF
Some general variable description.

Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

If this is a map, information about keys and values meaning should be included.

If values are nested maps, a list of keys/properties could follow:
  - `name_of_property` - (`variable_type`|`required`) some short description.
  - `example_string_required` - (`string`|`required`) for required properties
  - `example_bool_optional` - (`bool`|`false`) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional` - (`string`|`module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional` - (`number`|`cloud default`) when property is not required and we rely on the defaults set by the cloud API

Example

example blocks could follow here
EOF
```

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_example_docs"></a> [example\_docs](#input\_example\_docs) | Some general variable description.<br><br>Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. <br><br>If this is a map, information about keys and values meaning should be included.<br><br>If values are nested maps, a list of keys/properties could follow:<br>  - `name_of_property` - (`variable_type`\|`required`) some short description.<br>  - `example_string_required` - (`string`\|`required`) for required properties<br>  - `example_bool_optional` - (`bool`\|`false`) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional` - (`string`\|`module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional` - (`number`\|`cloud default`) when property is not required and we rely on the defaults set by the cloud API<br><br>Example<br><br>example blocks could follow here | `any` | n/a | yes |

Second proposal is similar, with additional alignment in the description - this ha no impact on the generated table row, but is easier to read in the `variables.tf` directly.

```hcl
description = <<-EOF
Some general variable description.

Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

If this is a map, information about keys and values meaning should be included.

If values are nested maps, a list of keys/properties could follow:
  - `name_of_property`        - (`variable_type`|`required`) some short description.
  - `example_string_required` - (`string`|`required`) for required properties
  - `example_bool_optional`   - (`bool`|`false`) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional` - (`string`|`module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional` - (`number`|`cloud default`) when property is not required and we rely on the defaults set by the cloud API

Example

example blocks could follow here
EOF
```

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_example_docs"></a> [example\_docs](#input\_example\_docs) | Some general variable description.<br><br>Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. <br><br>If this is a map, information about keys and values meaning should be included.<br><br>If values are nested maps, a list of keys/properties could follow:<br>  - `name_of_property`        - (`variable_type`\|`required`) some short description.<br>  - `example_string_required` - (`string`\|`required`) for required properties<br>  - `example_bool_optional`   - (`bool`\|`false`) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional` - (`string`\|`module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional` - (`number`\|`cloud default`) when property is not required and we rely on the defaults set by the cloud API<br><br>Example<br><br>example blocks could follow here | `any` | n/a | yes |

Third proposal removes additional code markers within the braces. The most important part - property name - is emphasized, its description, including type etc. is in the same line, still easy to find and read.

```hcl
description = <<-EOF
Some general variable description.

Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

If this is a map, information about keys and values meaning should be included.

If values are nested maps, a list of keys/properties could follow:
  - `name_of_property`        - (variable_type|required) some short description.
  - `example_string_required` - (string|required) for required properties
  - `example_bool_optional`   - (bool|false) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional` - (string|module default) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional` - (number|cloud default) when property is not required and we rely on the defaults set by the cloud API

Example

example blocks could follow here
EOF
```

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_example_docs"></a> [example\_docs](#input\_example\_docs) | Some general variable description.<br><br>Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. <br><br>If this is a map, information about keys and values meaning should be included.<br><br>If values are nested maps, a list of keys/properties could follow:<br>  - `name_of_property`        - (variable\_type\|required) some short description.<br>  - `example_string_required` - (string\|required) for required properties<br>  - `example_bool_optional`   - (bool\|false) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional` - (string\|module default) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional` - (number\|cloud default) when property is not required and we rely on the defaults set by the cloud API<br><br>Example<br><br>example blocks could follow here | `any` | n/a | yes |

**Comment by FoSix** [comment]
@michalbil : 
- 1<sup>st</sup> suggestion 👍🏻 
- 2<sup>nd</sup> i do agree, it can be troublesome, as this would be manual work, but yes, it's more readable
- 3<sup>rd</sup> I would keep the emphasis, sometimes there's a lot of text in a single line that could cause the defaults and data type to blur into background. It does not have to be a `code block`, we could do *italics* for example

**Comment by FoSix** [comment]
Another idea would be to split the important and not important properties into to two lists. This can be optional, but would become handy for large modules, like `vmss` or `appgw`. Sometimes you're not interested in all options available, or the default suit VMSERIES quite good, so it's a waste of time to mix them with the required/important ones. 

One thing more is that the list of required/important props is usually shorter, so the top of the documentation would be less cluttered.

Another option is to add some HTML tags like `<detailed>` to allow some folding when displaying the documentation on GH/TF Registry.

So the `description` would look like this:

```hcl
description = <<-EOF
Some general variable description.

Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq.....

If this is a map, information about keys and values meaning should be included.

Required/important/without defaults, etc:
  - `name_of_property`: (`variable_type` | `required`) some short description.
  - `example_string_required`: (`string` | `required`) for required properties
  - `example_bool_optional`: (`bool` | `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional`: (`string` | `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional`: (`number` | `cloud default`) when property is not required and we rely on the defaults set by the cloud API

<details>
<summary>Optional/not required/with defaults, etc:</summary>
  - `name_of_property`: (`variable_type` | `required`) some short description.
  - `example_string_required`: (`string` | `required`) for required properties
  - `example_bool_optional`: (`bool` | `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional`: (`string` | `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional`: (`number` | `cloud default`) when property is not required and we rely on the defaults set by the cloud API
  - `name_of_property`: (`variable_type` | `required`) some short description.
  - `example_string_required`: (`string` | `required`) for required properties
  - `example_bool_optional`: (`bool` | `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value
  - `example_string_optional`: (`string` | `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`
  - `example_number_optional`: (`number` | `cloud default`) when property is not required and we rely on the defaults set by the cloud API
</details>

<details>
<summary>Examples</summary>
  example blocks could follow here
</details>

EOF
```

This would render into:
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_test"></a> [test](#input\_test) | Some general variable description.<br><br>Some longer description if required: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq.....<br><br>If this is a map, information about keys and values meaning should be included.<br><br>Required/important/without defaults, etc:<br>  - `name_of_property`: (`variable_type` \| `required`) some short description.<br>  - `example_string_required`: (`string` \| `required`) for required properties<br>  - `example_bool_optional`: (`bool` \| `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional`: (`string` \| `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional`: (`number` \| `cloud default`) when property is not required and we rely on the defaults set by the cloud API<br><br><details><br><summary>Optional/not required/with defaults, etc:</summary><br>  - `name_of_property`: (`variable_type` \| `required`) some short description.<br>  - `example_string_required`: (`string` \| `required`) for required properties<br>  - `example_bool_optional`: (`bool` \| `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional`: (`string` \| `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional`: (`number` \| `cloud default`) when property is not required and we rely on the defaults set by the cloud API<br>  - `name_of_property`: (`variable_type` \| `required`) some short description.<br>  - `example_string_required`: (`string` \| `required`) for required properties<br>  - `example_bool_optional`: (`bool` \| `false`) when property is not required and we force a default value in the example, possibly overwrting the module default value<br>  - `example_string_optional`: (`string` \| `module default`) when property is not required and we rely on module's defaults, this implicitly states that the variable defined in a module has `nullable` set to `false`<br>  - `example_number_optional`: (`number` \| `cloud default`) when property is not required and we rely on the defaults set by the cloud API<br></details><br><br><details><br><summary>Examples</summary><br>  example blocks could follow here<br></details> | `map` | `{}` | no |

**Comment by FoSix** [comment]
an example, a sum of all above suggestions can be found:

- for `variables.tf` format -> [here](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/82370696752ed913e697945e114e4d0830fe4fa6/examples/dedicated_vmseries_and_autoscale/variables.tf#L258)
- for `README.md` look -> [here](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/tree/257-unify-the-format-of-variables-documentation/examples/dedicated_vmseries_and_autoscale#input_vmss)

**Comment by FoSix** [comment]
all ideas gathered there will be used in #307
