### ISSUE TITLE
[Bug Report] Panorama Module "boot_diagnostics.0.storage_uri" is required, but no definition was found.

### ISSUE THREAD

**Issue by PenDrag0n7** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#364]
### Describe the bug

I set the boot_diagnostic_storage_uri to null but it still asking for the url.

```
│ Error: Missing required argument
│
│   with module.panorama["panorama-ae"].azurerm_virtual_machine.panorama,
│   on .terraform\modules\panorama\modules\panorama\main.tf line 79, in resource "azurerm_virtual_machine" "panorama":
│   79:     storage_uri = var.boot_diagnostic_storage_uri
│
│ The argument "boot_diagnostics.0.storage_uri" is required, but no definition was found.
╵
```

### Module Version

1.2.2

### Terraform version

 v1.5.6

### Expected behavior

Should allow to skip the need to set storage account for bootdiag

### Anything else to add?

Problematic code in panorama module

  boot_diagnostics {
    enabled     = var.boot_diagnostic_storage_uri != null ? true : false
    storage_uri = var.boot_diagnostic_storage_uri
  }

**Comment by FoSix** [comment]
@PenDrag0n7 - thanks for pointing that out. I think we missed that because everyone is used to a workaround you can find in the [panorama example](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/main/examples/standalone_panorama/main.tf#L73).

But you're right, the code should work with just the defaults. A fix is coming.
